Listen to product details events
vtex-apps/google-analytics pull request #1
Opened 2019-04-30 17:09 UTC by italo-batista

#### What is the purpose of this pull request?

Lestening to productDetails event

#### Types of changes

* [ ] Bug fix (a non-breaking change which fixes an issue)
* [X] New feature (a non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Requires change to documentation, which has been updated accordingly.

2019-04-30 17:21 UTC, gustavorosolem commented on react/index.tsx
> +ga('create', 'UA-XXXXX-Y');
Por que tem dois create e com o código genérico?

2019-04-30 17:29 UTC, italo-batista commented on react/index.tsx
> +ga('create', 'UA-XXXXX-Y');
Erro meu. Só deveria ter inserido a linha logo abaixo a essa.

2019-04-30 18:19 UTC, gustavorosolem requested changes

2019-04-30 18:19 UTC, gustavorosolem commented on react/index.tsx
> +window.addEventListener('message', e => {
Por que não usar o mesmo addEventListener que já existe apenas adicionando o IF dentro dele?
Outra coisa, esta sendo disparado o `ga('send', 'pageview')` neste `e.data.event === 'productView'`, porém o `case 'pageView'` e `case 'pageInfo'` também disparam o `ga('send', 'pageview')`.
Confirmar se não esta sendo enviado duas vezes o `ga('send', 'pageview')` quando acessa o detalhe do produto, caso esteja, o registro esta sendo enviado duplicado.

2019-05-02 17:59 UTC, gustavorosolem approved these changes
LGTM

2019-05-03 13:22 UTC, gustavorosolem approved these changes

2019-05-03 14:01 UTC, brunojdo approved these changes

2019-05-06 19:37 UTC, merged