Disptach productClick event to google-analytics
vtex-apps/google-analytics pull request #4
Opened 2019-05-10 13:05 UTC by italo-batista

#### What is the purpose of this pull request?

Listen to productClicks events and dispatch them to google-analytics view.

#### Types of changes

* [ ] Bug fix (a non-breaking change which fixes an issue)
* [X] New feature (a non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Requires change to documentation, which has been updated accordingly.

**workspace**: https://spaceodyssey--storecomponents.myvtex.com

2019-05-10 13:18 UTC, gustavorosolem approved these changes

2019-05-10 17:21 UTC, lucis approved these changes

2019-05-10 17:43 UTC, klzns requested changes

2019-05-10 17:43 UTC, klzns commented on react/utils.tsx
> +export const getCategory = (rawCategories: any) => {
Add types

2019-05-10 17:43 UTC, klzns commented on react/index.tsx
> +const productClick = (product: any) => {
Add types

2019-05-14 11:58 UTC, klzns submitted a review, later dismissed

2019-05-14 11:58 UTC, klzns commented on react/index.tsx
> +    variant: product.variant,
I think Bruno is using `product.skuName` instead

2019-05-15 19:02 UTC, merged